# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kec.v1 import kec_pb2 as kec_dot_v1_dot_kec__pb2


class KECServiceStub(object):
    """Serviço KEC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/darwin.kec.v1.KECService/Analyze',
                request_serializer=kec_dot_v1_dot_kec__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisResponse.FromString,
                )
        self.StreamData = channel.stream_stream(
                '/darwin.kec.v1.KECService/StreamData',
                request_serializer=kec_dot_v1_dot_kec__pb2.DataChunk.SerializeToString,
                response_deserializer=kec_dot_v1_dot_kec__pb2.ProcessedChunk.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/darwin.kec.v1.KECService/HealthCheck',
                request_serializer=kec_dot_v1_dot_kec__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=kec_dot_v1_dot_kec__pb2.HealthCheckResponse.FromString,
                )


class KECServiceServicer(object):
    """Serviço KEC
    """

    def Analyze(self, request, context):
        """Análise única (síncrona)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamData(self, request_iterator, context):
        """Streaming bi-direcional para datasets grandes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KECServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=kec_dot_v1_dot_kec__pb2.AnalyzeRequest.FromString,
                    response_serializer=kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisResponse.SerializeToString,
            ),
            'StreamData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=kec_dot_v1_dot_kec__pb2.DataChunk.FromString,
                    response_serializer=kec_dot_v1_dot_kec__pb2.ProcessedChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=kec_dot_v1_dot_kec__pb2.HealthCheckRequest.FromString,
                    response_serializer=kec_dot_v1_dot_kec__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'darwin.kec.v1.KECService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KECService(object):
    """Serviço KEC
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.kec.v1.KECService/Analyze',
            kec_dot_v1_dot_kec__pb2.AnalyzeRequest.SerializeToString,
            kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/darwin.kec.v1.KECService/StreamData',
            kec_dot_v1_dot_kec__pb2.DataChunk.SerializeToString,
            kec_dot_v1_dot_kec__pb2.ProcessedChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.kec.v1.KECService/HealthCheck',
            kec_dot_v1_dot_kec__pb2.HealthCheckRequest.SerializeToString,
            kec_dot_v1_dot_kec__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
