# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from physioqm.v1 import physioqm_pb2 as physioqm_dot_v1_dot_physioqm__pb2


class PhysioQMServiceStub(object):
    """============================================================================
    PhysioQM Service - Quantum-Informed PBPK Prediction
    ============================================================================

    Multi-scale integration: Quantum → Enzyme → Transporter → Physiology

    Author: Agourakis
    Created: 2025-10-31T01:15:00Z
    Purpose: Real science - mechanistic PBPK prediction
    Darwin Indexed: Auto-indexed via MCP
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictPBPK = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/PredictPBPK',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.PredictRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.PBPKPredictionResponse.FromString,
                )
        self.ExtractQuantumFeatures = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/ExtractQuantumFeatures',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.QuantumRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.QuantumFeaturesResponse.FromString,
                )
        self.DockToCYP450 = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/DockToCYP450',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.DockingRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.DockingScoresResponse.FromString,
                )
        self.PredictTransporters = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/PredictTransporters',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.TransporterRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.TransporterResponse.FromString,
                )
        self.GenerateVisualMaps = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/GenerateVisualMaps',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.VisualRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.VisualMapsResponse.FromString,
                )
        self.ExplainPrediction = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/ExplainPrediction',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.ExplainRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.ExplanationResponse.FromString,
                )
        self.GetAttentionWeights = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/GetAttentionWeights',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.AttentionRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.AttentionResponse.FromString,
                )
        self.StreamPredictions = channel.stream_stream(
                '/darwin.physioqm.v1.PhysioQMService/StreamPredictions',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.PredictRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.PBPKPredictionResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/darwin.physioqm.v1.PhysioQMService/HealthCheck',
                request_serializer=physioqm_dot_v1_dot_physioqm__pb2.HealthRequest.SerializeToString,
                response_deserializer=physioqm_dot_v1_dot_physioqm__pb2.HealthResponse.FromString,
                )


class PhysioQMServiceServicer(object):
    """============================================================================
    PhysioQM Service - Quantum-Informed PBPK Prediction
    ============================================================================

    Multi-scale integration: Quantum → Enzyme → Transporter → Physiology

    Author: Agourakis
    Created: 2025-10-31T01:15:00Z
    Purpose: Real science - mechanistic PBPK prediction
    Darwin Indexed: Auto-indexed via MCP
    ============================================================================

    """

    def PredictPBPK(self, request, context):
        """Main prediction endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractQuantumFeatures(self, request, context):
        """Feature extraction endpoints (for debugging/inspection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DockToCYP450(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictTransporters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateVisualMaps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainPrediction(self, request, context):
        """Interpretation endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttentionWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredictions(self, request_iterator, context):
        """Batch processing (for large datasets)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhysioQMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictPBPK': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPBPK,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.PredictRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.PBPKPredictionResponse.SerializeToString,
            ),
            'ExtractQuantumFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractQuantumFeatures,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.QuantumRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.QuantumFeaturesResponse.SerializeToString,
            ),
            'DockToCYP450': grpc.unary_unary_rpc_method_handler(
                    servicer.DockToCYP450,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.DockingRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.DockingScoresResponse.SerializeToString,
            ),
            'PredictTransporters': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTransporters,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.TransporterRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.TransporterResponse.SerializeToString,
            ),
            'GenerateVisualMaps': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateVisualMaps,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.VisualRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.VisualMapsResponse.SerializeToString,
            ),
            'ExplainPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainPrediction,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.ExplainRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.ExplanationResponse.SerializeToString,
            ),
            'GetAttentionWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttentionWeights,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.AttentionRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.AttentionResponse.SerializeToString,
            ),
            'StreamPredictions': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredictions,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.PredictRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.PBPKPredictionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=physioqm_dot_v1_dot_physioqm__pb2.HealthRequest.FromString,
                    response_serializer=physioqm_dot_v1_dot_physioqm__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'darwin.physioqm.v1.PhysioQMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhysioQMService(object):
    """============================================================================
    PhysioQM Service - Quantum-Informed PBPK Prediction
    ============================================================================

    Multi-scale integration: Quantum → Enzyme → Transporter → Physiology

    Author: Agourakis
    Created: 2025-10-31T01:15:00Z
    Purpose: Real science - mechanistic PBPK prediction
    Darwin Indexed: Auto-indexed via MCP
    ============================================================================

    """

    @staticmethod
    def PredictPBPK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/PredictPBPK',
            physioqm_dot_v1_dot_physioqm__pb2.PredictRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.PBPKPredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExtractQuantumFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/ExtractQuantumFeatures',
            physioqm_dot_v1_dot_physioqm__pb2.QuantumRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.QuantumFeaturesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DockToCYP450(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/DockToCYP450',
            physioqm_dot_v1_dot_physioqm__pb2.DockingRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.DockingScoresResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictTransporters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/PredictTransporters',
            physioqm_dot_v1_dot_physioqm__pb2.TransporterRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.TransporterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateVisualMaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/GenerateVisualMaps',
            physioqm_dot_v1_dot_physioqm__pb2.VisualRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.VisualMapsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExplainPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/ExplainPrediction',
            physioqm_dot_v1_dot_physioqm__pb2.ExplainRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.ExplanationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttentionWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/GetAttentionWeights',
            physioqm_dot_v1_dot_physioqm__pb2.AttentionRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.AttentionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPredictions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/darwin.physioqm.v1.PhysioQMService/StreamPredictions',
            physioqm_dot_v1_dot_physioqm__pb2.PredictRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.PBPKPredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/darwin.physioqm.v1.PhysioQMService/HealthCheck',
            physioqm_dot_v1_dot_physioqm__pb2.HealthRequest.SerializeToString,
            physioqm_dot_v1_dot_physioqm__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
