# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kec.v1 import kec_pb2 as kec_dot_v1_dot_kec__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kec/v1/kec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KECServiceStub(object):
    """Service para análise KEC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/darwin.kec.v1.KECService/Analyze',
                request_serializer=kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisRequest.SerializeToString,
                response_deserializer=kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisResponse.FromString,
                _registered_method=True)
        self.StreamData = channel.stream_stream(
                '/darwin.kec.v1.KECService/StreamData',
                request_serializer=kec_dot_v1_dot_kec__pb2.DataChunk.SerializeToString,
                response_deserializer=kec_dot_v1_dot_kec__pb2.DataChunk.FromString,
                _registered_method=True)


class KECServiceServicer(object):
    """Service para análise KEC
    """

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KECServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisRequest.FromString,
                    response_serializer=kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisResponse.SerializeToString,
            ),
            'StreamData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=kec_dot_v1_dot_kec__pb2.DataChunk.FromString,
                    response_serializer=kec_dot_v1_dot_kec__pb2.DataChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'darwin.kec.v1.KECService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('darwin.kec.v1.KECService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KECService(object):
    """Service para análise KEC
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/darwin.kec.v1.KECService/Analyze',
            kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisRequest.SerializeToString,
            kec_dot_v1_dot_kec__pb2.ScaffoldAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/darwin.kec.v1.KECService/StreamData',
            kec_dot_v1_dot_kec__pb2.DataChunk.SerializeToString,
            kec_dot_v1_dot_kec__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
